exceptions = {
    "A Zverev":"Alexander Zverev",
    "M Zverev":"Mischa Zverev",
    "A de Minaur":"Alex De Minaur",
    "M Ymer":"Mikael Ymer",
    "E Ymer":"Elias Ymer",
    "M Berrettini":"Matteo Berrettini",
    "J Berrettini":"Jacopo Berrettini",
    "A Ramos-Vinolas":"Albert Ramos",
    "L Harris":"Lloyd Harris",
    "P Martinez":"Pedro Martinez",
    "F Auger-Aliassime":"Felix Auger Aliassime",
    "T Daniel":"Taro Daniel",
    "B van de Zandschulp":"Botic van de Zandschulp",
    "J Sousa":"Joao Sousa",
    "P Sousa":"Pedro Sousa",
    "E Gomez":"Emilio Gomez",
    "D Novak":"Dennis Novak",
    "B van de Zandschulp":"Botic Van De Zandschulp",
    "M McDonald":"Mackenzie Mcdonald",
    "C O'Connell":"Christopher Oconnell",
    "JM Cerundolo":"Juan Manuel Cerundolo",
    "F Cerundolo":"Francisco Cerundolo"
}